### ISSUE TITLE
Better naming for provisioning profile env variables

### ISSUE THREAD

**Issue by Neil3079** [theappbusiness/MasterFastfile#18]
Currently the environment variables relating to provisioning profiles are not clear to the user.

`TAB_PROVISIONING_PROFILE` is for setting the profile
`TAB_PROVISIONING_PROFILE_PATH` is for installing it in the build machine

I propose we change these variable names to be more explicit, something like the following;

`TAB_SIGNING_WITH_PROVISIONING_PROFILE`
`TAB_INSTALL_PROVISIONING_PROFILE_PATH` for installing it in the build machine

Seeing as this is a breaking change it will be part of the 3.0.0 release if implemented

**Comment by lucianomarisi** [comment]
This change makes sense to me.

**Comment by NikolaKirev** [comment]
Sounds good. Only comment I have is that `TAB_SIGNING_WITH_PROVISIONING_PROFILE` reads a bit like a boolean on/off switch. How about `TAB_SIGNING_WITH_PROVISIONING_PROFILE_NAME`?

**Comment by Neil3079** [comment]
Sounds good, but the above makes me think we are just signing with a name, perhaps `TAB_SIGNING_WITH_PROVISIONING_PROFILE_NAMED` just to make it super explicit?

**Comment by KITSTABLucianoMarisi** [comment]
In Xcode 8 don't we specify a name anyways? meaning that we sort of _sign with a name_?

**Comment by lucianomarisi** [comment]
In Xcode 8 don't we specify a name anyways? meaning that we sort of _sign with a name_?

**Comment by Neil3079** [comment]
I have always seen it as I specify a provisioning profile by providing a name. The phrase _signing with provisioning profile_ name doesn't make sense imo, but _signing with provisioning profile named_ reads like how I would expect, happy to be overruled on this if people don't agree though, either one is still way better than what we currently have!

**Comment by NikolaKirev** [comment]
I like how `_NAME` end in a noun, but I agree that `_NAMED` is even more explicit and descriptive.
