### ISSUE TITLE
Provide better documentation around Provfile and how it is created.

### ISSUE THREAD

**Issue by NikolaKirev** [theappbusiness/MasterFastfile#29]
I was trying to set up one of my projects that has multiple extensions to use `MasterFastfile` and was initially unsure on where the `Provfile` comes from.

**Comment by KaneCheshire** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #29: Provide better documentation around Provfile and how it is created.](https://trello.com/c/zzrGRomY/23-issue-29-provide-better-documentation-around-provfile-and-how-it-is-created)
