### ISSUE TITLE
Release new version of masterfastfile

### ISSUE THREAD

**Issue by zacoid55** [theappbusiness/MasterFastfile#32]

**Comment by Neil3079** [comment]
The way we create a new version is by creating a new tag https://git-scm.com/book/en/v2/Git-Basics-Tagging. Is this a feature release?

**Comment by zacoid55** [comment]
@Neil3079 I think so? It's an added feature in terms of there being a dedicated UI testing lane now.

What do you think?

**Comment by Neil3079** [comment]
Yeah thats a new feature, we will bump to V2.3.0 

So what happens now is you create a PR into master, once that is merged we create a tag for the new version and people can start using it.
