### ISSUE TITLE
Default gym export options

### ISSUE THREAD

**Issue by Neil3079** [theappbusiness/MasterFastfile#33]
For many projects the following works for the export options

```
{
  "provisioningProfiles": {
   $(FL_UPDATE_PLIST_APP_IDENTIFIER): $(TAB_PROVISIONING_PROFILE)
  },
  "method": $(TAB_EXPORT_METHOD)
}
```

We should have this by default and allow people to override them

**Comment by KaneCheshire** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #29: Provide better documentation around Provfile and how it is created.](https://trello.com/c/zzrGRomY/23-issue-29-provide-better-documentation-around-provfile-and-how-it-is-created)

**Comment by KaneCheshire** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #33: Default gym export options](https://trello.com/c/KyU44UGC/24-issue-33-default-gym-export-options)
