### ISSUE TITLE
Rename hockey lane as this causes a fastlane warning

### ISSUE THREAD

**Issue by lucianomarisi** [theappbusiness/MasterFastfile#4]
Currently there is warning when using the MasterFastfile as there is a lane named `hockey` as well as an action:

> Name of the lane 'hockey' is already taken by the action named 'hockey

**Comment by Neil3079** [comment]
What shall we rename `hockey` too? `hockey_deploy`, `hockey_build` any preferences?

**Comment by lucianomarisi** [comment]
I'd go for `hockey_deploy` as I think that is clearer. Other alternatives could be `deploy_hockey`, `deploy_to_hockey`.

**Comment by Neil3079** [comment]
Yeah the only thing i don't like is we have a function called `deploy_hockey()` (used for common functionality between lanes `hockey` and `hockey_no_test`)

**Comment by lucianomarisi** [comment]
interesting, I wonder if we should have a convention for functions vs lanes even though I think they are the same as they are both valid ways of expressing functions in Ruby

**Comment by Neil3079** [comment]
So currently lanes are unique actions we want to run as part of testing and deployment and any common functionality is extracted to a function. I believe lanes show up in the command line docs making it easier for a user to know what they should be calling

**Comment by lucianomarisi** [comment]
maybe we can have clearer names for the lanes such as `deploy_hockey` or `deploy_to_hockey` as they are more visible in the docs and rename the internal functions to something more verbose or even prepended then we a dash (controversial!)?

**Comment by Neil3079** [comment]
by dash do you mean `_` or `-`? Im guessing dash so it would be more like 

`_buildAndDeployToHockey()`

for the function?

**Comment by lucianomarisi** [comment]
I meant underscore actually, `_`

**Comment by Neil3079** [comment]
Yeah sorry my typo, i meant to say underscore as well
