### ISSUE TITLE
Setting `TAB_USE_TIME_FOR_BUILD_NUMBER` to `FALSE` does not disable it

### ISSUE THREAD

**Issue by NikolaKirev** [theappbusiness/MasterFastfile#50]
When having this feature turned on for some environments like so:
`TAB_USE_TIME_FOR_BUILD_NUMBER=TRUE`

Temporarily disabling it using:
`TAB_USE_TIME_FOR_BUILD_NUMBER=FALSE`
... does not work.
The only way to disable it is to delete the line that defines the variable.

**Comment by KaneCheshire** [comment]
Do you not have to change it with `ENV["TAB_USE_TIME_FOR_BUILD_NUMBER"] = false` after it's initially defined?

**Comment by samdods** [comment]
it's because of where it's checked. it's just an environment variable, which is always of type string. setting to true or false won't make a difference.

we could (should?) change where it's checked to something like:
```
if ENV['TAB_USE...'].lowercase == "true" { ...
```

(not sure of ruby syntax for lowercase)

**Comment by NikolaKirev** [comment]
@samdods Yes. I believe that is what is causing it. The current check that we have check for existence of the variable and does not take the actual value into consideration.
